#!/usr/bin/env python3
"""Generate a TOC of every usable DaVinci Resolve plugin/effect/template on this
machine, and persist it so Claude knows what's available.

Runs the davinci-resolve-mcp scanners DIRECTLY (filesystem-only — no running
Resolve, no MCP-server restart needed), so it reflects the CURRENT code including
the .drfx-expansion fix. Outputs:
  * <out>.json  — full machine-readable manifest (source of truth for use-plugins)
  * <out>.md    — human-readable TOC
  * (optional) a bounded, auto-managed SUMMARY block in root CLAUDE.md
                (counts + packs + pointer — NOT the full list, to avoid context bloat)

Run with the MCP server's venv python so the package imports:
  <repo>/.venv/bin/python generate_plugin_toc.py \
      --out ./davinci-plugins --claude-md ./CLAUDE.md
"""
from __future__ import annotations

import argparse
import json
import os
import sys

CLAUDE_BEGIN = "<!-- BEGIN davinci-plugins (auto-generated by davinci-resolve-generate-plugin-list) -->"
CLAUDE_END = "<!-- END davinci-plugins -->"


def _load_scanners():
    """Import the fixed, filesystem-only scanners from the installed package."""
    try:
        from davinci_resolve_mcp.tools.fx_plugins import (  # noqa
            enumerate_templates, get_resolvefx_registry, enumerate_ofx,
        )
        return enumerate_templates, get_resolvefx_registry, enumerate_ofx
    except Exception as e:  # noqa: BLE001
        sys.exit(
            "Could not import davinci_resolve_mcp — run this with the MCP server's "
            f"venv python (e.g. <repo>/.venv/bin/python). Underlying error: {e}"
        )


def build_manifest(stamp: str) -> dict:
    enumerate_templates, get_resolvefx_registry, enumerate_ofx = _load_scanners()

    templates = json.loads(enumerate_templates(scope="all")).get("templates", [])
    resolvefx = json.loads(get_resolvefx_registry()).get("plugins", [])
    try:
        ofx_bundles = json.loads(enumerate_ofx()).get("plugins", [])
    except Exception:  # noqa: BLE001
        ofx_bundles = []

    # group templates by category; track which are insertable-by-name
    by_cat: dict[str, list] = {}
    packs: dict[str, dict] = {}
    for t in templates:
        cat = (t.get("category") or "Uncategorized")
        by_cat.setdefault(cat, []).append(t)
        pack = t.get("pack")
        if pack:
            p = packs.setdefault(pack, {})
            p[cat] = p.get(cat, 0) + 1

    manifest = {
        "generated": stamp,
        "counts": {
            "templates_total": len(templates),
            "templates_insertable": sum(1 for t in templates if t.get("insertable")),
            "resolvefx": len(resolvefx),
            "ofx_bundles": len(ofx_bundles),
            "by_category": {c: len(v) for c, v in sorted(by_cat.items())},
        },
        "packs": packs,
        # insertable title/generator names are the actionable ones for use-plugins
        "insertable_titles": sorted(
            t["insert_name"] for t in templates
            if t.get("insertable") and (t.get("category") or "").lower() in ("titles", "title")
        ),
        "insertable_generators": sorted(
            t["insert_name"] for t in templates
            if t.get("insertable") and (t.get("category") or "").lower() in ("generators", "generator")
        ),
        "transitions": sorted({t["insert_name"] for t in templates
                               if (t.get("category") or "").lower() == "transitions"}),
        "effects_templates": sorted({t["insert_name"] for t in templates
                                     if (t.get("category") or "").lower() == "effects"}),
        "resolvefx": [{"name": p["name"], "regid": p.get("wireId", "")} for p in resolvefx],
        "ofx_bundles": ofx_bundles,
    }
    return manifest


def render_md(m: dict) -> str:
    c = m["counts"]
    lines = [
        "# DaVinci Resolve — installed plugins & templates (TOC)",
        "",
        f"_Generated {m['generated']}. Machine-specific; regenerate after installing packs._",
        "",
        "## Summary",
        f"- **{c['templates_total']}** Fusion templates ({c['templates_insertable']} insertable by name)",
        f"- **{c['resolvefx']}** ResolveFX/OFX effects (apply to a clip)",
        f"- **{c['ofx_bundles']}** third-party OFX bundles",
        "- by category: " + ", ".join(f"{k} {v}" for k, v in c["by_category"].items()),
        "",
        "## Packs",
    ]
    for pack, cats in sorted(m["packs"].items()):
        lines.append(f"- **{pack}** — " + ", ".join(f"{k}:{v}" for k, v in sorted(cats.items())))
    lines += ["", "## Insertable titles (`insert_template_by_name kind=fusion_title`)"]
    lines += [f"- `{n}`" for n in m["insertable_titles"]]
    if m["insertable_generators"]:
        lines += ["", "## Insertable generators (`kind=fusion_generator`)"]
        lines += [f"- `{n}`" for n in m["insertable_generators"]]
    lines += ["", "## Transitions (GUI-only — no scripting API to insert a named transition)"]
    lines += [f"- {n}" for n in m["transitions"]]
    lines += ["", "## Effect templates (GUI-only)"]
    lines += [f"- {n}" for n in m["effects_templates"]]
    lines += ["", "## ResolveFX / OFX (apply via `apply_ofx_to_clip(regid=…)`, no `ofx.` prefix)"]
    lines += [f"- `{p['name']}` → `{p['regid']}`" for p in m["resolvefx"]]
    return "\n".join(lines) + "\n"


def render_claude_block(m: dict, manifest_md_path: str) -> str:
    c = m["counts"]
    cats = ", ".join(f"{k} {v}" for k, v in c["by_category"].items())
    packs = ", ".join(sorted(m["packs"].keys())) or "(none)"
    body = [
        CLAUDE_BEGIN,
        "## DaVinci Resolve plugins available (auto-generated summary)",
        f"This machine has **{c['templates_total']} Fusion templates** "
        f"({c['templates_insertable']} insertable by name: {cats}), "
        f"**{c['resolvefx']} ResolveFX/OFX** effects, and **{c['ofx_bundles']}** third-party OFX bundles.",
        f"Template packs: {packs}.",
        f"**Full names + regids are in [`{os.path.basename(manifest_md_path)}`]({manifest_md_path})** — "
        "read it before inserting titles or applying effects; use the "
        "`davinci-resolve-use-plugins` skill. Titles/generators are insertable via "
        "`insert_template_by_name`; transitions/effects packs are GUI-only.",
        CLAUDE_END,
    ]
    return "\n".join(body)


def upsert_claude_md(claude_path: str, block: str) -> str:
    existing = ""
    if os.path.isfile(claude_path):
        with open(claude_path) as f:
            existing = f.read()
    if CLAUDE_BEGIN in existing and CLAUDE_END in existing:
        pre = existing.split(CLAUDE_BEGIN)[0].rstrip()
        post = existing.split(CLAUDE_END, 1)[1].lstrip()
        new = (pre + "\n\n" + block + "\n\n" + post).strip() + "\n"
        action = "updated"
    else:
        new = (existing.rstrip() + "\n\n" + block + "\n").lstrip() if existing else block + "\n"
        action = "appended"
    with open(claude_path, "w") as f:
        f.write(new)
    return action


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate a DaVinci Resolve plugin/template TOC.")
    ap.add_argument("--out", default="./davinci-plugins", help="output basename (writes .json + .md)")
    ap.add_argument("--claude-md", default="", help="path to root CLAUDE.md to upsert a summary block")
    ap.add_argument("--stamp", default="", help="timestamp string to record (scripts can't call Date.now)")
    args = ap.parse_args()

    stamp = args.stamp or "(unstamped)"
    m = build_manifest(stamp)

    json_path = args.out + ".json"
    md_path = args.out + ".md"
    with open(json_path, "w") as f:
        json.dump(m, f, indent=2)
    with open(md_path, "w") as f:
        f.write(render_md(m))

    result = {"json": json_path, "md": md_path, "counts": m["counts"]}
    if args.claude_md:
        action = upsert_claude_md(args.claude_md, render_claude_block(m, md_path))
        result["claude_md"] = f"{action}: {args.claude_md}"
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
