#!/usr/bin/env python3
"""Generate a TOC of every usable DaVinci Resolve plugin/effect/template on this
machine — WITH a functional description for each — and persist it so Claude knows
what's available.

Descriptions come from two ACCURATE sources (nothing invented):
  * Fusion template packs (MotionVFX .drfx): the sub-group folder INSIDE the
    archive (e.g. "Titles › Infographics", "Titles › Social Media",
    "Titles › Call to Action", "Effects › Camera Movements") — this is what the
    pack author filed the template under, so it describes what it does.
  * ResolveFX: a curated one-line description per effect where known; otherwise a
    prettified name (never a fabricated behaviour).

Runs the davinci-resolve-mcp scanners DIRECTLY (filesystem-only — no running
Resolve, no MCP-server restart), reflecting the CURRENT code incl. the
.drfx-expansion fix. Outputs <out>.json + <out>.md, and (optional) a bounded
auto-managed summary block in root CLAUDE.md.

Run with the MCP server's venv python:
  <repo>/.venv/bin/python generate_plugin_toc.py --out ./davinci-plugins --claude-md ./CLAUDE.md
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import zipfile

CLAUDE_BEGIN = "<!-- BEGIN davinci-plugins (auto-generated by davinci-resolve-generate-plugin-list) -->"
CLAUDE_END = "<!-- END davinci-plugins -->"

# Curated one-liners for the editorially-useful ResolveFX. Keys are the registry
# `name`. Anything not here falls back to a prettified name (no invented behaviour).
RESOLVEFX_DESC = {
    "gaussianblur": "Soft Gaussian blur (blur in/out, defocus).",
    "boxblur": "Fast box blur.",
    "radialblur": "Blur radiating from a center point.",
    "zoomblur": "Blur along the zoom axis (punch-in energy).",
    "directionalblur": "Motion-style blur in one direction.",
    "lensblur": "Photographic depth-of-field blur with bokeh.",
    "mosaicblur": "Pixelate / censor region.",
    "prismblur": "Chromatic prism blur.",
    "glow": "Bloom/glow on highlights (dreamy lift).",
    "lightray": "Volumetric light rays / god-rays from highlights.",
    "lensflare": "Lens flare.",
    "lensreflections": "Anamorphic lens reflections.",
    "halationplugin": "Film halation glow around highlights.",
    "vignette": "Darken or lighten the frame edges (focus the eye).",
    "filmlook": "Film emulation (grain, halation, tone).",
    "filmdamage": "Aged/damaged film look (scratches, dust).",
    "filmgrain": "Add film grain.",
    "analogdamage": "Analog VHS/tape damage.",
    "jpegdamage": "JPEG compression artifacts.",
    "scanline": "CRT scanlines.",
    "scanlinev2": "CRT scanlines (v2).",
    "chromaticaberration": "Color-fringe lens aberration.",
    "sharpen": "Sharpen detail.",
    "sharpenedgeplugin": "Edge-aware sharpening.",
    "softsharpenskin": "Smooth or sharpen skin.",
    "beauty": "Skin smoothing / beauty.",
    "facerefinement": "AI face retouch (skin, eyes, lips).",
    "facerefinement2": "AI face retouch (v2).",
    "dehaze": "Remove atmospheric haze.",
    "contrastpop": "Local-contrast punch.",
    "texturepop": "Enhance fine texture.",
    "detailrecovery": "Recover fine detail.",
    "colorstabilizer": "Even out color/exposure flicker across a clip.",
    "deflicker": "Remove flicker.",
    "timelapsedeflicker": "Deflicker time-lapses.",
    "noisereduction": "Spatial/temporal noise reduction.",
    "videorestoration": "General footage cleanup.",
    "dropshadow": "Drop shadow (for keyed/graphic layers).",
    "defocusbackground": "Blur the background (fake shallow DoF).",
    "depthmap": "Generate a depth map.",
    "relight": "Add virtual lighting.",
    "vignette_": "",
    "colorspacetransform": "Convert between color spaces.",
    "colorspacetransformv2": "Convert between color spaces (v2).",
    "transform": "Pan/zoom/rotate as an effect.",
    "lensdistortion": "Add or correct lens distortion.",
    "warper": "Freeform mesh warp.",
    "smear": "Smear/stretch pixels.",
    "waviness": "Wavy distortion.",
    "ripple": "Ripple distortion.",
    "dent": "Bulge/pinch distortion.",
    "vortex": "Swirl distortion.",
    "mirror": "Kaleidoscope/mirror.",
    "stylize": "Stylize (posterize/abstract).",
    "watercolor": "Watercolor paint look.",
    "sketch": "Pencil-sketch look.",
    "emboss": "Emboss edges.",
    "edgedetect": "Outline edges.",
    "abstraction": "Abstract painterly look.",
    "invertcolor": "Invert colors.",
    "objectremoval": "AI remove a moving object.",
    "patchreplacer": "Clone/patch a region.",
    "smartroto": "AI roto/mask a subject.",
    "skyreplacement": "AI sky replacement.",
    "despillplugin": "Remove green/blue key spill.",
    "camerashake": "Add camera shake (energy).",
    "matchmove": "Match-move a layer to tracked motion.",
    "motionblur": "Add motion blur.",
    "motiontrails": "Echo/motion trails.",
    "stopmotion": "Stop-motion / frame-hold look.",
    "videocollage": "Multi-clip collage / split screen.",
    "grid": "Overlay a grid.",
    "falsecolor": "Exposure false-color overlay.",
    "tiltshiftblur": "Tilt-shift miniature blur.",
    "aperturediffraction": "Diffraction star highlights.",
    "flickeraddition": "Add flicker.",
    "burnaway": "Film burn-away transition look.",
    "shrinkandgrow": "Erode/dilate mattes.",
    "blankingfill": "Fill letterbox blanking.",
    "deband": "Remove color banding.",
    "dropshadow_": "",
}


def _pretty(name: str) -> str:
    return name.replace("plugin", "").replace("v2", " v2").replace("v3", " v3").strip().title()


def _resolvefx_desc(name: str) -> str:
    d = RESOLVEFX_DESC.get(name)
    return d if d else _pretty(name)


def _load_scanners():
    try:
        from davinci_resolve_mcp.tools.fx_plugins import (  # noqa
            enumerate_templates, get_resolvefx_registry, enumerate_ofx,
        )
        return enumerate_templates, get_resolvefx_registry, enumerate_ofx
    except Exception as e:  # noqa: BLE001
        sys.exit(
            "Could not import davinci_resolve_mcp — run with the MCP server's venv "
            f"python (<repo>/.venv/bin/python). Error: {e}"
        )


def _drfx_index(drfx_path: str) -> dict:
    """{setting_basename: {"group": sub-group folder, "member": internal zip path}}.

    A pack files templates as Edit/<Cat>/MotionVFX/<Pack>/<SubGroup>/.../<name>.setting.
    The sub-group (Typography / Social Media / Infographics / Tools / Logos / …) is a
    faithful description of what the template is for. ``member`` is the exact path
    inside the .drfx ZIP, so use-plugins can extract the .setting and apply it via
    ``apply_macro_to_clip`` (for Effects, or Titles applied as a macro). Flat packs
    yield group "".
    """
    out: dict = {}
    try:
        with zipfile.ZipFile(drfx_path) as zf:
            for n in zf.namelist():
                if "__MACOSX" in n or not n.lower().endswith(".setting"):
                    continue
                parts = n.split("/")
                group = ""
                if "MotionVFX" in parts:
                    i = parts.index("MotionVFX")
                    if i + 2 < len(parts) - 1:   # segment after <Pack>, not the filename
                        group = parts[i + 2]
                base = os.path.basename(n)[: -len(".setting")]
                if base:
                    out[base] = {"group": group, "member": n}
    except (zipfile.BadZipFile, OSError, RuntimeError):
        pass
    return out


def build_manifest(stamp: str) -> dict:
    enumerate_templates, get_resolvefx_registry, enumerate_ofx = _load_scanners()
    templates = json.loads(enumerate_templates(scope="all")).get("templates", [])
    resolvefx = json.loads(get_resolvefx_registry()).get("plugins", [])
    try:
        ofx_bundles = json.loads(enumerate_ofx()).get("plugins", [])
    except Exception:  # noqa: BLE001
        ofx_bundles = []

    # cache pack indexes per unique .drfx, then attach description + member to each row
    idx_cache: dict = {}
    for t in templates:
        pack_path = t.get("path", "")
        t["description"] = t.get("category", "")
        t["member"] = ""
        if pack_path.lower().endswith(".drfx"):
            if pack_path not in idx_cache:
                idx_cache[pack_path] = _drfx_index(pack_path)
            info = idx_cache[pack_path].get(t.get("insert_name", ""), {})
            group = info.get("group", "")
            cat = t.get("category", "")
            t["description"] = f"{cat} › {group}" if group else cat
            t["member"] = info.get("member", "")

    by_cat: dict = {}
    packs: dict = {}
    for t in templates:
        cat = t.get("category") or "Uncategorized"
        by_cat.setdefault(cat, []).append(t)
        pack = t.get("pack")
        if pack:
            packs.setdefault(pack, {})[cat] = packs.setdefault(pack, {}).get(cat, 0) + 1

    def rows(pred):
        return sorted(
            ({"name": t["insert_name"], "description": t.get("description", ""),
              "pack": t.get("pack", ""), "drfx": t.get("path", ""), "member": t.get("member", "")}
             for t in templates if pred(t)),
            key=lambda r: (r["description"], r["name"]),
        )

    lc = lambda t: (t.get("category") or "").lower()  # noqa: E731
    manifest = {
        "generated": stamp,
        "counts": {
            "templates_total": len(templates),
            "templates_insertable": sum(1 for t in templates if t.get("insertable")),
            "resolvefx": len(resolvefx),
            "ofx_bundles": len(ofx_bundles),
            "by_category": {c: len(v) for c, v in sorted(by_cat.items())},
        },
        "packs": packs,
        "insertable_titles": rows(lambda t: t.get("insertable") and lc(t) in ("titles", "title")),
        "insertable_generators": rows(lambda t: t.get("insertable") and lc(t) in ("generators", "generator")),
        "transitions": rows(lambda t: lc(t) == "transitions"),
        "effects_templates": rows(lambda t: lc(t) == "effects"),
        "resolvefx": [{"name": p["name"], "regid": p.get("wireId", ""),
                       "description": _resolvefx_desc(p["name"])} for p in resolvefx],
        "ofx_bundles": ofx_bundles,
    }
    return manifest


def _title_lines(header, rows):
    out = [f"### {header}"]
    for r in rows:
        d = f" — _{r['description']}_" if r["description"] else ""
        out.append(f"- `{r['name']}`{d}")
    return out


def render_md(m: dict) -> str:
    c = m["counts"]
    L = [
        "# DaVinci Resolve — installed plugins & templates (TOC)",
        "",
        f"_Generated {m['generated']}. Machine-specific; regenerate after installing packs._",
        "",
        "## Summary",
        f"- **{c['templates_total']}** Fusion templates ({c['templates_insertable']} insertable by name)",
        f"- **{c['resolvefx']}** ResolveFX/OFX effects (apply to a clip)",
        f"- **{c['ofx_bundles']}** third-party OFX bundles",
        "- by category: " + ", ".join(f"{k} {v}" for k, v in c["by_category"].items()),
        "",
        "## Packs",
    ]
    for pack, cats in sorted(m["packs"].items()):
        L.append(f"- **{pack}** — " + ", ".join(f"{k}:{v}" for k, v in sorted(cats.items())))
    L += ["", "## Insertable titles (`insert_template_by_name kind=fusion_title`)", ""]
    L += _title_lines("Titles", m["insertable_titles"])
    if m["insertable_generators"]:
        L += [""] + _title_lines("Generators (`kind=fusion_generator`)", m["insertable_generators"])
    L += ["", "## Transitions (GUI-only — no scripting API to insert a named transition)", ""]
    L += _title_lines("Transitions", m["transitions"])
    L += ["", "## Effect templates (GUI-only)", ""]
    L += _title_lines("Effects", m["effects_templates"])
    L += ["", "## ResolveFX / OFX (apply via `apply_ofx_to_clip(regid=…)`, no `ofx.` prefix)", ""]
    for p in m["resolvefx"]:
        L.append(f"- `{p['name']}` — {p['description']}  ·  `{p['regid']}`")
    return "\n".join(L) + "\n"


def render_claude_block(m: dict, manifest_md_path: str) -> str:
    c = m["counts"]
    cats = ", ".join(f"{k} {v}" for k, v in c["by_category"].items())
    packs = ", ".join(sorted(m["packs"].keys())) or "(none)"
    return "\n".join([
        CLAUDE_BEGIN,
        "## DaVinci Resolve plugins available (auto-generated summary)",
        f"This machine has **{c['templates_total']} Fusion templates** "
        f"({c['templates_insertable']} insertable by name: {cats}), "
        f"**{c['resolvefx']} ResolveFX/OFX** effects, and **{c['ofx_bundles']}** third-party OFX bundles.",
        f"Template packs: {packs}.",
        f"**Full names, descriptions & regids are in [`{os.path.basename(manifest_md_path)}`]"
        f"({manifest_md_path})** — read it before inserting titles or applying effects; use the "
        "`davinci-resolve-use-plugins` skill. Titles/generators are insertable via "
        "`insert_template_by_name`; transitions/effects packs are GUI-only.",
        CLAUDE_END,
    ])


def upsert_claude_md(claude_path: str, block: str) -> str:
    existing = ""
    if os.path.isfile(claude_path):
        with open(claude_path) as f:
            existing = f.read()
    if CLAUDE_BEGIN in existing and CLAUDE_END in existing:
        pre = existing.split(CLAUDE_BEGIN)[0].rstrip()
        post = existing.split(CLAUDE_END, 1)[1].lstrip()
        new = (pre + "\n\n" + block + "\n\n" + post).strip() + "\n"
        action = "updated"
    else:
        new = (existing.rstrip() + "\n\n" + block + "\n").lstrip() if existing else block + "\n"
        action = "appended"
    with open(claude_path, "w") as f:
        f.write(new)
    return action


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate a DaVinci Resolve plugin/template TOC with descriptions.")
    ap.add_argument("--out", default="./davinci-plugins")
    ap.add_argument("--claude-md", default="")
    ap.add_argument("--stamp", default="")
    args = ap.parse_args()

    m = build_manifest(args.stamp or "(unstamped)")
    json_path, md_path = args.out + ".json", args.out + ".md"
    with open(json_path, "w") as f:
        json.dump(m, f, indent=2)
    with open(md_path, "w") as f:
        f.write(render_md(m))

    result = {"json": json_path, "md": md_path, "counts": m["counts"]}
    if args.claude_md:
        result["claude_md"] = f"{upsert_claude_md(args.claude_md, render_claude_block(m, md_path))}: {args.claude_md}"
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
